/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-10-26 05:19:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hello_Doctor.dao.Reciver;
import com.hello_Doctor.util.AdminDbConnection;
import java.sql.Connection;
import java.util.List;
import com.hello_Doctor.dao.ViewDoctorByName;
import com.hello_Doctor.Model.Doctor;
import com.hello_Doctor.util.AdminDbConnection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import com.hello_Doctor.Model.Patient;

public final class BookAppointment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

Connection con = null;
	PreparedStatement ps = null;
	ResultSet rst = null;
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1619769352000L));
    _jspx_dependants.put("jar:file:/D:/hello_Doctor/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hello_Doctor/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098691290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("com.hello_Doctor.dao.ViewDoctorByName");
    _jspx_imports_classes.add("com.hello_Doctor.dao.Reciver");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("com.hello_Doctor.Model.Patient");
    _jspx_imports_classes.add("com.hello_Doctor.util.AdminDbConnection");
    _jspx_imports_classes.add("com.hello_Doctor.Model.Doctor");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Appointment Page</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Patient patient4 = (Patient) session.getAttribute("currentuser");
	if (patient4 == null) {
		response.sendRedirect("index.html");
	}

      out.write("\r\n");
      out.write("<nav id=\"navbar-example2\" class=\"navbar navbar-dark bg-dark\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"Menu.jsp\">HELLO DOCTOR</a>\r\n");
      out.write("\t\t<ul class=\"nav nav-pills\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<li class=\"nav-item\"><a class=\"nav-link\" >\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#profile\">Welcome,");
      out.print(patient4.getPatient_name());
      out.write("<br></a>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<div class=\"card\">\r\n");
      out.write("  <div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<form action=\"BookAppointment\" method=\"post\"\r\n");
      out.write("\t\t\t\t\t\tenctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table \">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"form-control\" name=\"fullname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Enter the full Name\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"email\" class=\"form-control\" name=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Enter the Email\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"tel\" class=\"form-control\" name=\"mobile\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tpattern=\"^\\d{3}\\d{3}\\d{4}$\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Enter the Mobile Number\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								String doctor_hospital = request.getParameter("doctor_hospital");
								con = AdminDbConnection.GetConnection();
								String sql = "select * from doctor where doctor_hospital=?";
								ps = con.prepareStatement(sql);
								ps.setString(1, doctor_hospital);
								rst = ps.executeQuery();
								while (rst.next()) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"doctor_hospital\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(rst.getString(7));
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input class=\"form-check-input\" type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"doctorname\" id=\"exampleRadios1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(rst.getString(2));
      out.write("\" checked> <label\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-check-label\" for=\"exampleRadios1\"> ");
      out.print(rst.getString(2));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</label></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label for=\"datepicker\" class=\"col-form-label\">Select\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tappointment date</label> <input placeholder=\"Date\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"date form-control\" id=\"datepicker\" type=\"date\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"date\" value=\"\" onfocus=\"this.value = '';\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = '';}\" required=\"\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><label for=\"datepicker\" class=\"col-form-label\">Select\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tappointment time</label> <select class=\"form-control\" name=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>Time Slot For Appointment</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>8:00AM-9:00AM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>9:00AM-10:00AM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>10:00AM-11:00AM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>11:00AM-12:00PM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>12:00PM-1:00PM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>1:00PM-2:00PM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>2:00PM-3:00PM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>3:00PM-4:00PM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>4:00PM-5:00PM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>5:00PM-6:00PM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>6:00PM-7:00PM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>7:00PM-8:00PM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>9:00PM-10:00PM</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><textarea class=\"form-control\" name=\"reason\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"Reason for Appointment\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\trows=\"\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select class=\"form-control\" name=\"type_of_appointment\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>Type of Appointment</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>Online</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>Offline</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"exampleFormControlFile1\">Upload File</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"file\" name=\"file\" class=\"form-control-file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"exampleFormControlFile1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">Confirm\r\n");
      out.write("\t\t\t\t\t\t\t\tAppointment</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- script -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- script end -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
