/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-10-26 05:18:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hello_Doctor.dao.UserDao;
import com.hello_Doctor.Model.AddHosp;

public final class EditHopsitalDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/AdminNavbar.jsp", Long.valueOf(1621489828000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.hello_Doctor.Model.AddHosp");
    _jspx_imports_classes.add("com.hello_Doctor.dao.UserDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Edit Hospital Details</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"assets/vendor/admin/vendor/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"assets/css/simple-sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"d-flex\" id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Sidebar -->\r\n");
      out.write("\t\t<div class=\"bg-light border-right\" id=\"sidebar-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"sidebar-heading\">HELLO DOCTOR</div>\r\n");
      out.write("\t\t\t<div class=\"list-group list-group-flush\">\r\n");
      out.write("\t\t\t\t<a href=\"AdminPannel.jsp\"\r\n");
      out.write("\t\t\t\t\tclass=\"list-group-item list-group-item-action bg-light\">Dashboard</a>\r\n");
      out.write("\t\t\t\t<a href=\"Registration_view.jsp\" class=\"list-group-item list-group-item-action bg-light\">Registration View</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"AddDoctor.jsp\" class=\"list-group-item list-group-item-action bg-light\">Add Doctor</a> \r\n");
      out.write("\t\t\t\t<a href=\"AddHosptial.jsp\" class=\"list-group-item list-group-item-action bg-light\">AddHosptialName</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<a href=\"AddHosptialDeatils.jsp\" class=\"list-group-item list-group-item-action bg-light\">AddHosptialDeatils</a>\r\n");
      out.write("\t\t\t\t<a href=\"UpdateHosptialDetails.jsp\" class=\"list-group-item list-group-item-action bg-light\">UpdateHosptialDetails</a> \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<a href=\"ContactView.jsp\" class=\"list-group-item list-group-item-action bg-light\">Contact View</a> \r\n");
      out.write("\t\t\t\t<a href=\"AppointmentView.jsp\" class=\"list-group-item list-group-item-action bg-light\">Appointment View </a>\r\n");
      out.write("\t\t\t\t<a href=\"AdminChat.jsp\" class=\"list-group-item list-group-item-action bg-light\">Chat</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /#sidebar-wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Page Content -->\r\n");
      out.write("\t\t<div id=\"page-content-wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<nav\r\n");
      out.write("\t\t\t\tclass=\"navbar navbar-expand-lg navbar-dark bg-dark border-bottom\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary\" id=\"menu-toggle\">Menu</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#navbarSupportedContent\"\r\n");
      out.write("\t\t\t\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav ml-auto mt-2 mt-lg-0\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- /#wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Bootstrap core JavaScript -->\r\n");
      out.write("\t<script src=\"assets/vendor/admin/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/vendor/admin/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Menu Toggle Script -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(\"#menu-toggle\").click(function(e) {\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t$(\"#wrapper\").toggleClass(\"toggled\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<h1>Edit Hospital Details</h1>\r\n");
      out.write("\r\n");

String hospital_id  = request.getParameter("hospital_id");
AddHosp  u = UserDao.getRecordById(Integer.parseInt(hospital_id));

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"UpdateConfrim\" method=\"post\">\r\n");
      out.write("<table class=\"table table-hover\">\r\n");
      out.write("<input type=\"hidden\" name=\"hospital_id\" value=\"");
      out.print(u.getHospital_id() );
      out.write("\"/>\r\n");
      out.write("<tr><td>Hospital_Name:</td><td><input type=\"text\" name=\"Hospital_Name\" value=\"");
      out.print( u.getHospital_name() );
      out.write("\"/></td></tr>\r\n");
      out.write("<tr><td>Hospital_no_of_doctor:</td><td><input type=\"number\" name=\"Hospital_no_of_doctor\" value=\"");
      out.print( u.getHospital_no_of_doctor() );
      out.write("\"/></td></tr>\r\n");
      out.write("<tr><td>Hospital_Address:</td><td><input type=\"text\" name=\"Hospital_Address\" value=\"");
      out.print( u.getHospital_address() );
      out.write("\"/></td></tr>\r\n");
      out.write("<tr><td>Hospital_city:</td><td><input type=\"text\" name=\"Hospital_city\" value=\"");
      out.print( u.getHospital_city() );
      out.write("\"/></td></tr>\r\n");
      out.write("<tr><td>Hospital_state:</td><td><input type=\"text\" name=\"Hospital_state\" value=\"");
      out.print( u.getHospital_state() );
      out.write("\"/></td></tr>\r\n");
      out.write("<tr><td>Hospital_zip:</td><td><input type=\"number\" name=\"Hospital_zip\" value=\"");
      out.print( u.getHospital_zip() );
      out.write("\"/></td></tr>\r\n");
      out.write("<tr><td> hospital_no_of_beds:</td><td><input type=\"number\" name=\"hospital_no_of_beds\" value=\"");
      out.print( u.getHospital_no_of_beds() );
      out.write("\"/></td></tr>\r\n");
      out.write("<tr><td>hospital_no_of_icu:</td><td><input type=\"number\"name=\"hospital_no_of_icu\" value=\"");
      out.print( u.getHospital_no_of_icu() );
      out.write("\"/></td></tr>\r\n");
      out.write("<tr><td> hospital_no_of_ot:</td><td><input type=\"number\" name=\"hospital_no_of_ot\" value=\"");
      out.print( u.getHospital_no_of_ot() );
      out.write("\"/></td></tr>\r\n");
      out.write("<tr><td> hospital_emergency:</td><td> \r\n");
      out.write("<select class=\"form-control\" id=\"\" name=\"hospital_emergency\" required=\"required\" >\r\n");
      out.write("        <option selected>Emergency</option>\r\n");
      out.write("        <option>Yes</option>\r\n");
      out.write("         <option>No</option>\r\n");
      out.write("           </select></tr>\r\n");
      out.write("<tr><td>hospital_contactno:</td><td><input type=\"tel\" name=\"hospital_contactno\" value=\"");
      out.print( u.getHospital_contactno() );
      out.write("\"/></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("<tr><td colspan=\"\"><input type=\"submit\" class=\"btn btn-primary\" value=\"UpdateDetails\"/></td></tr>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
